package:
  name: mosh
  version: master

source:
  git_url: https://github.com/mobile-shell/mosh
  git_tag: master
  git_depth: 1

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libprotobuf
    - ncurses
    - zlib
    - openssl
    - perl
  run:
    - libprotobuf
    - ncurses
    - zlib
    - openssl
    - perl

test:
  commands:
    - mosh-server -h

about:
  home: https://mosh.org/
  license: GPLv3+
  license_family: GPL3
  license_file: COPYING
  summary: 'Mobile shell that supports roaming and intelligent local echo'

  description: |
    Mosh is a remote terminal application that supports:
      - intermittent network connectivity,
      - roaming to different IP address without dropping the connection, and
      - intelligent local echo and line editing to reduce the effects
        of "network lag" on high-latency connections.
