package:
  name: neovim-qt
  version: master

source:
  git_url: https://github.com/equalsraf/neovim-qt
  git_tab: master
  git_depth: 1
  patches:
    - "win32alt.patch"

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - qt
  run:
    - qt
