package:
  name: emacs
  version: 27.0

source:
  git_url: git://git.sv.gnu.org/emacs.git
  git_tag: emacs-27
  git_depth: 1

build:
  number: 2
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
  host:
    - libxml2
    - ncurses
    - dbus  # [osx]
    - jpeg
    - libpng
    - libtiff
    - librsvg
    - giflib
    - gnutls
    - freetype # [linux]
    - xorg-libxaw # [linux]
    - xorg-libxpm # [linux]
    - zlib

  run:
    - libxml2
    - ncurses
    - dbus  # [osx]
    - jpeg
    - libpng
    - libtiff
    - librsvg
    - giflib
    - gnutls
    - freetype        # [linux]
    - xorg-libxaw  # [linux]
    - xorg-libxpm  # [linux]
    - xorg-libxfixes  # [linux]
    - xorg-libxft  # [linux]
    - zlib

test:
  commands:
    - $PREFIX/bin/emacs --help
    - $PREFIX/bin/emacsclient --help
    - $PREFIX/bin/ctags --help
    - $PREFIX/bin/ebrowse --help
    - $PREFIX/bin/etags --help
    - $PREFIX/bin/emacs -nw -Q --kill --batch

about:
  home: http://www.gnu.org/software/emacs/
  license: GPL-3.0
  summary: 'GNU Emacs is an extensible, customizable text editor.'
  license_file: COPYING
